#!/bin/bash

LOG_FILE="/var/log/xklb.log"
XKLB_EXECUTABLE="${XKLB_EXECUTABLE:-lb}"
TMP_DOWNLOADS_DIR="/library/downloads/calibre-web"
SURVEY_DB_FILE="${TMP_DOWNLOADS_DIR}/survey.db"
URL="$1"
FORMAT_OPTIONS="--format best --format-sort 'tbr~1000'"
XKLB_FULL_CMD="${XKLB_EXECUTABLE} tubeadd ${SURVEY_DB_FILE} ${URL} --verbose && ${XKLB_EXECUTABLE} dl ${SURVEY_DB_FILE} --prefix ${TMP_DOWNLOADS_DIR} --write-thumbnail ${FORMAT_OPTIONS} --video ${URL} --verbose"

mkdir -p ${TMP_DOWNLOADS_DIR}

# Function to log messages (and errors especially!)
log() {
    echo "$(date +'%Y-%m-%d %H:%M:%S') - $1" | tee -a ${LOG_FILE}
}

if ! command -v "${XKLB_EXECUTABLE}"; then
    log "xklb could not be found. Please install xklb and try again."
    exit 1
fi

if [ $# -eq 0 ]; then
    log "No arguments provided. Please provide a URL to download."
    exit 1
fi

# URL validation already taken care of by cps/static/js/main.js Line ~194,
# which prepends https:// if URL doesn't already begin with http:// or https://
# (Test below meant well, to enforce with logging, but violates "SSOT" --
# preconditions should be enforced in 1 single place if possible!)
# if [[ ! ${URL} =~ ^http[s]?:// ]]; then
#     log 'Invalid URL: xklb commands require URLs begin with "http://" or "https://"'
#     exit 1
# fi

if mv ${SURVEY_DB_FILE} ${SURVEY_DB_FILE}.$(date +%F_%T_%Z) 2> /dev/null; then
    log "Old ${SURVEY_DB_FILE} moved aside."
fi

log "Running command: ${XKLB_FULL_CMD}"
if OUTPUT=$(${XKLB_FULL_CMD}); then
    log "Download completed successfully."
else
    log "An error occurred while running the command. Output: ${OUTPUT}"
    exit 1
fi
