name: Integration Tests

on:
  pull_request:
    branches:
      - main  # Triggers when a PR is opened to main

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    env:
      TESTING_REPO_NAME: wafik97/API_calibre_web
      UI_TESTING_WORKFLOW_ID: smokeTest.yaml

    steps:
      - name: Trigger the Selenium testing workflow
        run: |
          curl -X POST \
           -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN_GITHUB }}" \
           -H "Accept: application/vnd.github.v3+json" \
           -d "{\"ref\": \"${{ github.head_ref }}\", \"inputs\": {\"chrome_131_0\": true}}" \
           https://api.github.com/repos/$TESTING_REPO_NAME/actions/workflows/$UI_TESTING_WORKFLOW_ID/dispatches
