name: Load Test with Locust

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  load_test:
    #if: github.event.pull_request.merged == true  # Ensures it runs only when merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Locust
        run: |
          python -m pip install --upgrade pip
          pip install locust

      - name: Run Small Load Test
        run: |
          locust -f locustFile.py --headless --users 5 --spawn-rate 2 --run-time 10s --html=report_small.html --csv=report_small

      - name: Run Medium Load Test
        run: |
          locust -f locustFile.py --headless --users 20 --spawn-rate 5 --run-time 20s --html=report_medium.html --csv=report_medium

      - name: Run Large Load Test
        run: |
          locust -f locustFile.py --headless --users 50 --spawn-rate 10 --run-time 30s --html=report_large.html --csv=report_large

      - name: Upload Small Test Report
        uses: actions/upload-artifact@v4
        with:
          name: locust-small-test
          path: report_small.html

      - name: Upload Medium Test Report
        uses: actions/upload-artifact@v4
        with:
          name: locust-medium-test
          path: report_medium.html

      - name: Upload Large Test Report
        uses: actions/upload-artifact@v4
        with:
          name: locust-large-test
          path: report_large.html
