name: CalibreWeb tests

on:
  pull_request:

jobs:
  TriggerDeployment:
    name: Trigger UI Testing Workflow
    runs-on: ubuntu-latest

    env:
      TESTING_REPO_NAME: wafik97/API_calibre_web
      UI_TESTING_WORKFLOW_ID: smokeTest.yaml
      PYTHON_TESTING_WORKFLOW_ID: pythonTest.yaml
    steps:
      - name: Trigger the Selenium testing workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"ref\": \"main\", \"inputs\": {\"grid_url\": \"http://localhost:4444\", \"chrome_131_0\": true}}" \
            https://api.github.com/repos/$TESTING_REPO_NAME/actions/workflows/$UI_TESTING_WORKFLOW_ID/dispatches

      - name: Trigger the Calibre testing workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"ref\": \"main\"}" \
            https://api.github.com/repos/$TESTING_REPO_NAME/actions/workflows/$PYTHON_TESTING_WORKFLOW_ID/dispatches
