name: CalibreWeb tests

on:
  pull_request:
    branches:
      - main

jobs:
  TriggerDeployment:
    name: Trigger UI Testing Workflow
    runs-on: ubuntu-latest
    needs: Test
    env:
      SPOTIFY_TESTING_REPO_NAME: wafik97/API_calibre_web
      UI_TESTING_WORKFLOW_ID: smokeTest.yaml
    steps:
      - name: Trigger the Selenium testing workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"ref\": \"main\", \"inputs\": {\"grid_url\": \"http://localhost:4444\", \"chrome_131_0\": true}}" \
            https://api.github.com/repos/$SPOTIFY_TESTING_REPO_NAME/actions/workflows/$UI_TESTING_WORKFLOW_ID/dispatches
